#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/admin
-
- name: Install Apache & PHP
  apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
    state: present
    update_cache: yes

- name: Activate Apache mod_php
  command: a2enmod php8.2
  ignore_errors: yes

- name: Copy Apache configuration
  copy:
    src: admin.conf
    dest: /etc/apache2/sites-available/admin.conf

- name: Activate the website
  command: a2ensite admin.conf

- name: Create upload directory
  file:
    path: /var/www/html/upload
    state: directory
    owner: www-data
    group: www-data
    mode: '0777'

- name: Copy website files
  copy:
    src: site/
    dest: /var/www/html
    mode: '0755'
    owner: www-data
    group: www-data

- name: Deactivate default site
  command: a2dissite 000-default.conf
  ignore_errors: yes

- name: Delete index.html of Apache
  file:
    path: /var/www/html/index.html
    state: absent

- name: Restart Apache
  service:
    name: apache2
    state: restarted

- name: Create user beer
  user:
    name: beer
    comment: "User for pentest lab"
    password: "{{ 'cuveedestrolls' | password_hash('sha512') }}"
    shell: /bin/bash
    create_home: yes

- name: Add beer to sudoers with full access and no password prompt
  copy:
    dest: /etc/sudoers.d/beer
    content: "beer ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: '0440'


- name: Ensure the repository .ssh exist
  file:
    path: /home/beer/.ssh
    state: directory
    owner: beer
    group: beer
    mode: '0700'

- name: Gen SSH key pair
  community.crypto.openssh_keypair:
    path: /home/beer/.ssh/id_rsa
    type: rsa
    size: 2048
    owner: beer
    group: beer
    mode: '0600'
  register: ssh_keypair
