- name: Install PostgreSQL packages
  apt:
    name:
      - postgresql
      - python3-psycopg2
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes


- name: Configurer la locale
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    line: "en_US.UTF-8 UTF-8"
    state: present
  become: yes

- name: Générer la locale
  ansible.builtin.command: locale-gen
  become: yes

- name: Mettre à jour la locale par défaut
  ansible.builtin.command: update-locale LANG=en_US.UTF-8
  become: yes

- name: Vérifier les locales générées
  ansible.builtin.command: locale -a
  register: locale_output
  become: yes

- debug:
    var: locale_output.stdout_lines



- name: Create Zabbix database
  postgresql_db:
    name: zabbix
    encoding: UTF8
    state: present
  become_user: postgres

- name: Create Zabbix DB user
  postgresql_user:
    name: zabbix
    password: zabbix
    state: present
  become_user: postgres


