---
- name: Créer un utilisateur pour Martin
  user:
    name: martin
    state: present
    groups: ""
    shell: /bin/bash

- name: Restreindre les permissions du home de martin
  file:
    path: /home/martin
    state: directory
    owner: martin
    group: martin
    mode: '0755'

- name: Copier le script de backup
  copy:
    src: backup.sh
    dest: /home/martin/backup.sh
    mode: '0755'

- name: Copier le premier flag
  copy:
    src: userflag.txt
    dest: /home/martin/userflag.txt
    mode: '0755'

- name: Copier le second flag
  copy:
    src: rootflag.txt
    dest: /root/rootflag.txt
    mode: '0755'

  
- name: Supprimer martin du groupe sudo s'il y est
  user:
    name: martin
    groups: ""
    append: no
    remove: yes

- name: Autoriser martin à exécuter backup.sh sans mot de passe
  lineinfile:
    path: /etc/sudoers.d/martin_backup
    create: yes
    mode: '0440'
    owner: root
    group: root
    line: 'martin ALL=(ALL) NOPASSWD: /home/martin/backup.sh'

- name: Autoriser martin à conserver PATH et désactiver secure_path
  copy:
    dest: /etc/sudoers.d/env_keep_martin
    content: |
      Defaults:martin !secure_path
      Defaults:martin env_keep += "PATH"
    owner: root
    group: root
    mode: '0440'


- name: Assurer que le dossier .ssh existe avec les bons droits
  file:
    path: /home/martin/.ssh
    state: directory
    owner: martin
    group: martin
    mode: '0700'

- name: Générer une paire de clés SSH pour martin
  community.crypto.openssh_keypair:
    path: /home/martin/.ssh/id_rsa
    type: rsa
    size: 2048
    owner: martin
    group: martin
    mode: '0600'
  register: ssh_keypair

- name: Mettre la clé publique dans authorized_keys
  authorized_key:
    user: martin
    key: "{{ ssh_keypair.public_key }}"

- name: Créer dossier /var/notes
  file:
    path: /var/notes
    state: directory
    owner: root
    group: www-data
    mode: '0750'

- name: Lire la clé privée dans une variable
  slurp:
    src: /home/martin/.ssh/id_rsa
  register: private_key_content
  become: true
  become_user: root

- name: Convertir la clé privée en texte lisible
  set_fact:
    private_key_text: "{{ private_key_content.content | b64decode }}"

- name: Copier la clé privée dans notes.txt avec message
  copy:
    content: |
      Au cas ou je l'oublierai, ma clef ssh :

      {{ private_key_text }}
    dest: /var/notes/notes.txt
    owner: root
    group: www-data
    mode: '0640'
