---
# tasks file for zabbix_agent
- name: Installer le paquet Zabbix agent
  apt:
    name: zabbix-agent
    state: present
    update_cache: yes

- name: Déployer la configuration de l'agent
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart zabbix agent

- name: S'assurer que l'agent est démarré et activé
  service:
    name: zabbix-agent
    state: started
    enabled: yes