---
- name: Déploiement complet de la machine Bodega
  hosts: bodega
  become: true
  vars_files:
    - role_bodega_users/vars/main.yml
    - role_bodega_web/vars/main.yml

  roles:
    - role_bodega_users
    - role_bodega_web
