---
- name: Installer Apache, PHP et MariaDB
  apt:
    name:
      - apache2
      - php
      - php-mysql
      - mariadb-server
    state: present
    update_cache: yes

- name: Installer zip
  apt:
    name: zip
    state: present
  become: true

- name: Installer dépendances Python pour MySQL
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes

- name: Démarrer MariaDB
  service:
    name: mariadb
    state: started
    enabled: true

- name: Créer l'utilisateur MySQL ansible_admin avec tous les privilèges
  community.mysql.mysql_user:
    name: "{{ mysql_ansible_user }}"
    password: "{{ mysql_ansible_password }}"
    host: localhost
    priv: '*.*:ALL,GRANT'
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Créer la base de données blogetu
  community.mysql.mysql_db:
    name: blogetu
    state: present
    login_user: "{{ mysql_ansible_user }}"
    login_password: "{{ mysql_ansible_password }}"

- name: Créer l'utilisateur blogetu_user et lui accorder des privilèges
  community.mysql.mysql_user:
    name: "{{ mysql_blogetu_user }}"
    password: "{{ mysql_blogetu_password }}"
    priv: 'blogetu.*:ALL'
    host: localhost
    state: present
    login_user: "{{ mysql_ansible_user }}"
    login_password: "{{ mysql_ansible_password }}"

# --- Création des tables ---

- name: Créer la table users si elle n'existe pas
  community.mysql.mysql_query:
    login_user: "{{ mysql_blogetu_user }}"
    login_password: "{{ mysql_blogetu_password }}"
    login_db: blogetu
    query: |
      CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(255) NOT NULL UNIQUE,
        password_hash VARCHAR(255) NOT NULL,
        is_admin TINYINT(1) DEFAULT 0
      );

- name: Créer la table messages si elle n'existe pas
  community.mysql.mysql_query:
    login_user: "{{ mysql_blogetu_user }}"
    login_password: "{{ mysql_blogetu_password }}"
    login_db: blogetu
    query: |
      CREATE TABLE IF NOT EXISTS messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        content TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
      );

- name: Désactiver les contraintes de clé étrangère
  community.mysql.mysql_query:
    login_user: "{{ mysql_blogetu_user }}"
    login_password: "{{ mysql_blogetu_password }}"
    login_db: blogetu
    query: SET FOREIGN_KEY_CHECKS=0;

- name: Vider la table messages avec DELETE
  community.mysql.mysql_query:
    login_user: "{{ mysql_blogetu_user }}"
    login_password: "{{ mysql_blogetu_password }}"
    login_db: blogetu
    query: DELETE FROM messages;

- name: Vider la table users avec DELETE
  community.mysql.mysql_query:
    login_user: "{{ mysql_blogetu_user }}"
    login_password: "{{ mysql_blogetu_password }}"
    login_db: blogetu
    query: DELETE FROM users;

- name: Réactiver les contraintes de clé étrangère
  community.mysql.mysql_query:
    login_user: "{{ mysql_blogetu_user }}"
    login_password: "{{ mysql_blogetu_password }}"
    login_db: blogetu
    query: SET FOREIGN_KEY_CHECKS=1;

- name: Insérer un utilisateur 
  community.mysql.mysql_query:
    login_user: "{{ mysql_blogetu_user }}"
    login_password: "{{ mysql_blogetu_password }}"
    login_db: blogetu
    query: |
      INSERT IGNORE INTO users (username, password_hash, is_admin)
      VALUES ('martin', 'a86222b593d488c39006853850916ef0', 1);

- name: Insérer un utilisateur mael
  community.mysql.mysql_query:
    login_user: "{{ mysql_blogetu_user }}"
    login_password: "{{ mysql_blogetu_password }}"
    login_db: blogetu
    query: |
      INSERT IGNORE INTO users (username, password_hash, is_admin)
      VALUES ('mael', '718cbd44c3b53052e12dc8c7a75815dc', 0);

- name: Insérer un utilisateur de test
  community.mysql.mysql_query:
    login_user: "{{ mysql_blogetu_user }}"
    login_password: "{{ mysql_blogetu_password }}"
    login_db: blogetu
    query: |
      INSERT IGNORE INTO users (username, password_hash, is_admin)
      VALUES ('testuser', 'a471055764b536d206b007f164241150', 0);

- name: Insérer un message de bienvenue lié à l'utilisateur admin
  community.mysql.mysql_query:
    login_user: "{{ mysql_blogetu_user }}"
    login_password: "{{ mysql_blogetu_password }}"
    login_db: blogetu
    query: |
      INSERT IGNORE INTO messages (user_id, content)
      SELECT id, 'Bienvenue sur Blogetu !'
      FROM users
      WHERE username = 'mael';

- name: Créer un dossier pour le site
  file:
    path: /var/www/html
    state: directory
    mode: '0755'


- name: Copier les fichiers du domaine 
  copy:
    src: site/
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copier la configuration Apache du site principal (domaine principal)
  copy:
    src: 1-bodega.conf
    dest: /etc/apache2/sites-available/1-bodega.conf
  notify: Restart Apache

- name: Copier la configuration Apache du sous-domaine blog
  copy:
    src: 2-blog.conf
    dest: /etc/apache2/sites-available/2-blog.conf
  notify: Restart Apache

- name: Désactiver le VirtualHost par défaut
  command: a2dissite 000-default.conf
  args:
    removes: "/etc/apache2/sites-enabled/000-default.conf"
  notify: Restart Apache

- name: Activer le VirtualHost principal (domaine principal)
  command: a2ensite 1-bodega.conf
  args:
    creates: "/etc/apache2/sites-enabled/1-bodega.conf"
  notify: Restart Apache

- name: Activer le VirtualHost blog (sous-domaine)
  command: a2ensite 2-blog.conf
  args:
    creates: "/etc/apache2/sites-enabled/2-blog.conf"
  notify: Restart Apache

- name: Activer les modules Apache nécessaires
  command: a2enmod rewrite
  notify: Restart Apache

- name: Déployer les fichiers du sous-domaine blog
  copy:
    src: "{{ item }}"
    dest: "/var/www/blog/{{ item | basename }}"
    owner: www-data
    group: www-data
    mode: '0644'
  loop:
    - blog/php/login.php
    - blog/php/admin.php
    - blog/php/blog.php
    - blog/php/db.php
    - blog/php/logout.php
    - blog/styles2.css
    - blog/login.html
    - blog/index.html

- name: Ajouter un fichier .htaccess pour blog (sécuriser le dossier PHP)
  copy:
    src: blog/.htaccess
    dest: /var/www/blog/.htaccess
    owner: www-data
    group: www-data
    mode: '0644'

- name: Redémarrer Apache
  service:
    name: apache2
    state: restarted
    enabled: true