all:
  children:
    bodega:
      hosts:
        bodega-host:
          ansible_host: "{{ ip_bodega_public }}"
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/mykey
          ansible_python_interpreter: /usr/bin/python3

    lenox:
      hosts:
        lenox-host:
          ansible_host: "{{ ip_lenox_public }}"
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/mykey
          ansible_python_interpreter: /usr/bin/python3

    lenox_private:
      hosts:
        pv-lenox-host:
          ansible_host: "{{ ip_lenox_private }}"
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/mykey
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_common_args: >
            -o IdentitiesOnly=yes
            -o StrictHostKeyChecking=no
            -o ProxyCommand="ssh -i ~/.ssh/mykey -W %h:%p ec2-user@{{ bastion_ip }}"

    wazuh_agent:
      hosts:
        wazuh-agent-lenox:
          ansible_host: "{{ ip_lenox_wazuh }}"
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/mykey
          ansible_ssh_common_args: >
            -o StrictHostKeyChecking=no
            -o ProxyCommand="ssh -i ~/.ssh/mykey -W %h:%p ec2-user@{{ bastion_ip }}"

        wazuh-agent-bodega:
          ansible_host: "{{ ip_bodega_private }}"
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/mykey
          ansible_ssh_common_args: >
            -o StrictHostKeyChecking=no
            -o ProxyCommand="ssh -i ~/.ssh/mykey -W %h:%p ec2-user@{{ bastion_ip }}"

        wazuh-agent-pv-lenox:
          ansible_host: "{{ ip_lenox_private }}"
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/mykey
          ansible_ssh_common_args: >
            -o StrictHostKeyChecking=no
            -o ProxyCommand="ssh -i ~/.ssh/mykey -W %h:%p ec2-user@{{ bastion_ip }}"

    wazuh_server:
      hosts:
        wazuh-server:
          ansible_host: "{{ ip_wazuh_server }}"
          ansible_user: wazuh-user
          ansible_ssh_private_key_file: ~/.ssh/mykey
          ansible_ssh_common_args: >
            -o StrictHostKeyChecking=no
            -o ProxyCommand="ssh -i ~/.ssh/mykey -W %h:%p ec2-user@{{ bastion_ip }}"

    zabbix_server:
      hosts:
        zabbix-server:
          ansible_host: "{{ ip_zabbix_server }}"
          ansible_user: rocky
          ansible_ssh_private_key_file: ~/.ssh/mykey
          ansible_ssh_common_args: >
            -o StrictHostKeyChecking=no
            -o ProxyCommand="ssh -i ~/.ssh/mykey -W %h:%p ec2-user@{{ bastion_ip }}"

    zabbix_agent:
      hosts:
        zabbix-agent-lenox:
          ansible_host: "{{ ip_lenox_wazuh }}"
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/mykey
          ansible_ssh_common_args: >
            -o StrictHostKeyChecking=no
            -o ProxyCommand="ssh -i ~/.ssh/mykey -W %h:%p ec2-user@{{ bastion_ip }}"

        zabbix-agent-bodega:
          ansible_host: "{{ ip_bodega_private }}"
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/mykey
          ansible_ssh_common_args: >
            -o StrictHostKeyChecking=no
            -o ProxyCommand="ssh -i ~/.ssh/mykey -W %h:%p ec2-user@{{ bastion_ip }}"
