- name: Installer Apache
  apt:
    name: apache2
    update_cache: yes
    state: present

- name: Créer dossier vide pour catch-all
  file:
    path: /var/www/empty
    state: directory
    mode: '0755'

- name: Copier les fichiers du site principal
  copy:
    src: site/
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copier les fichiers du sous-domaine blogetu
  copy:
    src: blogetu/
    dest: /var/www/blogetu/
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copier la configuration Apache du site principal
  copy:
    src: 1-bodega.conf
    dest: /etc/apache2/sites-available/1-bodega.conf
  notify: Restart Apache

- name: Copier la configuration Apache du sous-domaine
  copy:
    src: 2-blogetu.conf
    dest: /etc/apache2/sites-available/2-blogetu.conf
  notify: Restart Apache

- name: Désactiver le VirtualHost par défaut
  command: a2dissite 000-default.conf
  args:
    removes: "/etc/apache2/sites-enabled/000-default.conf"
  notify: Restart Apache

- name: Activer le VirtualHost principal (1-bodega.conf)
  command: a2ensite 1-bodega.conf
  args:
    creates: "/etc/apache2/sites-enabled/1-bodega.conf"
  notify: Restart Apache

- name: Activer le VirtualHost blogetu (2-blogetu.conf)
  command: a2ensite 2-blogetu.conf
  args:
    creates: "/etc/apache2/sites-enabled/2-blogetu.conf"
  notify: Restart Apache

- name: Activer les modules Apache nécessaires
  command: a2enmod rewrite
  notify: Restart Apache

- name: Démarrer Apache
  service:
    name: apache2
    state: started
    enabled: true
