---
- name: Establish SSH tunnel to Wazuh dashboard
  become: yes
  local_action:
    module: shell
    cmd: ssh -L 1234:10.0.1.50:443 -i {{ key_path }} -o "ProxyCommand=ssh -i {{ key_path }} -W %h:%p ec2-user@{{ ec2_public_ip }}" wazuh-user@10.0.1.50
  async: 0
  poll: 0


