---

- name: Mettre à jour le système
  apt:
    update_cache: true
    upgrade: dist

- name: Télécharger le dépôt Zabbix
  get_url:
    url: "{{ zabbix_repo_deb }}"
    dest: /tmp/zabbix-release.deb

- name: Installer le dépôt Zabbix
  apt:
    deb: /tmp/zabbix-release.deb

- name: Rafraîchir le cache APT
  apt:
    update_cache: true

- name: Installer les paquets nécessaires
  apt:
    name:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-agent2
      - mariadb-server
    state: present

- name: Démarrer et activer MariaDB
  service:
    name: mariadb
    state: started
    enabled: true

- name: Créer la base de données Zabbix
  mysql_db:
    name: "{{ zabbix_db_name }}"
    encoding: utf8
    collation: utf8_bin
    state: present

- name: Créer l utilisateur de la base de données
  mysql_user:
    name: "{{ zabbix_db_user }}"
    password: "{{ zabbix_db_password }}"
    priv: "{{ zabbix_db_name }}.*:ALL"
    host: localhost
    state: present

- name: Importer le schéma SQL de Zabbix
  shell: |
    zcat /usr/share/doc/zabbix-sql-scripts/mysql/server.sql.gz | mysql -u{{ zabbix_db_user }} -p{{ zabbix_db_password }} {{ zabbix_db_name }}
  args:
    creates: /var/lib/mysql/{{ zabbix_db_name }}

- name: Configurer le mot de passe dans zabbix_server.conf
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^#?DBPassword='
    line: "DBPassword={{ zabbix_db_password }}"

- name: Définir le timezone PHP dans Apache
  lineinfile:
    path: /etc/zabbix/apache.conf
    regexp: '^php_value date.timezone'
    line: "php_value date.timezone {{ zabbix_timezone }}"

- name: Redémarrer et activer les services Zabbix
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - zabbix-server
    - zabbix-agent2
    - apache2
