---
# tasks file for wazuh_agents

- name: Update system
  apt:
    update_cache: yes
    upgrade: yes

- name: Install required dependencies
  apt:
    name:
      - curl
      - apt-transport-https
      - lsb-release
    state: present

- name: Add Wazuh GPG key
  shell: |
    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -

- name: Add Wazuh repository
  shell: |
    echo "deb https://packages.wazuh.com/4.x/apt/ stable main" > /etc/apt/sources.list.d/wazuh.list

- name: Update package list
  apt:
    update_cache: yes

- name: Install Wazuh agent
  environment:
    WAZUH_MANAGER: "10.0.0.2"
  apt:
    name: wazuh-agent
    state: present

- name: Enable and start Wazuh agent service
  systemd:
    name: wazuh-agent
    enabled: yes
    state: started
