---
- name: Installer Apache
  apt:
    name: apache2
    update_cache: yes
    state: present

- name: Copier les fichiers du site principal
  copy:
    src: site/
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copier les fichiers du sous-domaine blogetu
  copy:
    src: blogetu/
    dest: /var/www/blogetu/
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copier la configuration Apache du sous-domaine
  copy:
    src: blogetu.conf
    dest: /etc/apache2/sites-available/blogetu.conf

- name: Activer le VirtualHost blogetu
  command: a2ensite blogetu.conf
  notify: Restart Apache

- name: Activer les modules Apache nécessaires
  command: a2enmod rewrite
  notify: Restart Apache

- name: Démarrer Apache
  service:
    name: apache2
    state: started
    enabled: true

- name: Lancer le simulateur de Martin
  copy:
    src: site/martin_simulator.sh
    dest: /usr/local/bin/martin_simulator.sh
    mode: '0755'

- name: Démarrer martin_simulator au boot (crontab)
  cron:
    name: "Simuler Martin"
    job: "@reboot /usr/local/bin/martin_simulator.sh"