---
- name: Créer un utilisateur pour Martin
  user:
    name: martin
    state: present
    groups: sudo
    shell: /bin/bash

- name: Copier le script de backup
  copy:
    src: backup.sh
    dest: /home/martin/backup.sh
    mode: '0755'

- name: Assurer que le dossier .ssh existe avec les bons droits
  file:
    path: /home/martin/.ssh
    state: directory
    owner: martin
    group: martin
    mode: '0700'

- name: Générer une paire de clés SSH pour martin
  community.crypto.openssh_keypair:
    path: /home/martin/.ssh/id_rsa
    type: rsa
    size: 2048
    owner: martin
    group: martin
    mode: '0600'
  register: ssh_keypair

- name: Mettre la clé publique dans authorized_keys
  authorized_key:
    user: martin
    key: "{{ ssh_keypair.public_key }}"

- name: Créer dossier /var/notes accessible par www-data mais hors web
  file:
    path: /var/notes
    state: directory
    owner: root
    group: www-data
    mode: '0750'

- name: Lire la clé privée dans une variable
  slurp:
    src: /home/martin/.ssh/id_rsa
  register: private_key_content
  become: true
  become_user: root

- name: Convertir la clé privée en texte lisible
  set_fact:
    private_key_text: "{{ private_key_content.content | b64decode }}"

- name: Copier la clé privée dans notes.txt avec message
  copy:
    content: |
      Au cas ou je l'oublierai, ma clef ssh :

      {{ private_key_text }}
    dest: /var/notes/notes.txt
    owner: root
    group: www-data
    mode: '0640'
