---
# Ajouter un utilisateur
- name: Créer un utilisateur pour Martin
  user:
    name: martin
    state: present
    groups: sudo
    shell: /bin/bash

# Copier le script de backup
- name: Copier le script de backup
  copy:
    src: backup.sh
    dest: /usr/local/bin/backup.sh
    mode: '0755'
