#SPDX-License-Identifier: MIT-0
---
# tasks file for role_lenox_users

- name: Create "lenox" user
  user:
    name: lenox
    shell: /bin/bash
    create_home: yes

- name: Copy backup.sh file
  copy:
    src: backup.sh
    dest: /home/lenox/backup.sh
    owner: lenox
    mode: '0755'
