- name: Créer un utilisateur "lenox"
  user:
    name: lenox
    shell: /bin/bash
    create_home: yes

- name: Copier le script de backup
  copy:
    src: backup.sh
    dest: /home/lenox/backup.sh
    owner: lenox
    mode: '0755'
