#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/privesc

- name: Ensure webadmin user exists
  user:
    name: "webadmin"
    state: present
    shell: /bin/bash

- name: Copy backup.sh file
  copy:
    src: backup.sh
    dest: /home/webadmin/backup.sh
    owner: "webadmin"
    group: "webadmin"
    mode: '0755'

- name: Ensure the repository .ssh exist
  file:
    path: /home/webadmin/.ssh
    state: directory
    owner: webadmin
    group: webadmin
    mode: '0700'

- name: Gen SSH key pair
  community.crypto.openssh_keypair:
    path: /home/webadmin/.ssh/id_rsa
    type: rsa
    size: 2048
    owner: webadmin
    group: webadmin
    mode: '0600'
  register: ssh_keypair

- name: Copy secret file
  copy:
    src: invoice-tutorial.pdf
    dest: /root/invoice-tutorial.pdf
    owner: "root"
    group: "root"
    mode: '0600'

- name: Ensure cron is installed
  apt:
    name: cron
    state: present
    update_cache: yes

- name: Ensure cron service is running and enabled
  service:
    name: cron
    state: started
    enabled: yes

- name: Add cron job as root
  cron:
    name: "Run backup script"
    user: root
    minute: "*/2"
    job: "/home/webadmin/backup.sh"