- name: Deploy Lenox
  hosts: lenox
  become: yes

  roles:
    - lenox_users
    - lenox_web
    - cockpit
    - privesc

- name: Deploy Bodega
  hosts: bodega
  become: true
  vars_files:
    - roles/role_bodega_users/vars/main.yml
    - roles/role_bodega_web/vars/main.yml

  roles:
    - role_bodega_users
    - role_bodega_web

- name: Deploy Private Lenox
  hosts: lenox_private
  become: yes

  roles:
    - admin

- name: Deploy Wazuh
  hosts: wazuh_server 
  become: yes
  roles:
    - wazuh_configuration

- name: Deploy Wazuh agent
  hosts: wazuh_agent
  become: yes
  roles:
    - wazuh_agents

# - name: Deploy zabbix server
#   hosts: zabbix_server
#   become: yes
#   roles:
#    - zabbix_server

- name: Deploy zabbix agent
  hosts: zabbix_agent
  become: true
  become_user: root
  roles:
    - zabbix_agent
