collections:
  - name: community.mysql
  - name: community.zabbix
    version: 3.3.0
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 3.7.0
  - name: community.postgresql

