all:
  children:
    lenox_private:
      hosts:
        10.0.1.10:
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/mykey
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_common_args: >
            -o IdentitiesOnly=yes -o ProxyCommand="ssh -i ~/.ssh/mykey -W %h:%p ec2-user@51.44.226.200"
